# -*- coding: utf-8 -*-
"""DataCleaning/Transformation -- Replacing Null Values & adding "AvgSalary" Column

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SSjOtgrVwTSTatRQuujfryKQ9SGEvN2A

Dennis Kain -- replacing 0 in "Yearly Max" column and replacing them as null values
"""

#Replacing 0 in 'Yearly Max' as "Null"

import pandas as pd

df = pd.read_csv('FinalJobData.csv')

# Replace all "0" values in the 'Yearly Max' column with 'Null'
df['Yearly Max'] = df['Yearly Max'].replace(0, 'Null')

# Save the updated CSV file
df.to_csv('FinalJobData1.csv', index=False)

#Creating a new column called "Average Salary"

import pandas as pd
import numpy as np

df = pd.read_csv('FinalJobData1.csv')

# Replace 'Null' values with np.nan
df = df.replace('Null', np.nan)

# Convert the 'Yearly Max' and 'Yearly Min' columns to float
df['Yearly Max'] = df['Yearly Max'].astype(float)
df['Yearly Min'] = df['Yearly Min'].astype(float)

# Calculate the average salary
df['Average Salary'] = (df['Yearly Max'] + df['Yearly Min']) / 2



df.to_csv('FinalJobData2.csv', index=False)